		<script src="js/script_perfil.js"></script>
		<script src="js/filtrar_produtos.js"></script>
		<script src="js/script_lista_produtos.js"></script>
		<script src="js/script_lista_usuarios.js"></script>
		<script src="js/script_mudar_cargo.js"></script>
		<script src="js/script_cadastro_produto.js"></script>
		<script src="js/script_carrinho.js"></script>
<footer>
    <div id="copy-area">
        <div class="container">
            <div class="col-md-12">
                <p>@Desenvolvido por <a href="" target="_blank">TCC Group</a> &copy; 2021</p>
            </div>
        </div>
    </div>
</footer>