<header>
    <!-- NavBar -->
    <div class="container" id="nav-container">
        <nav class = "navbar navbar-expand-lg fixed-top navbar-dark">
            <a href="img/logo.png" class="navbar-brand">
                <img  id="logo" src="img/Logo.png" alt="Logo Site" href="index.html"> Nome Empresa
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-links" 
                aria-controls="navbar-links" aria-expanded="false" aria-label="Toggle navigation">
                <span class = "navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbar-links">
                <div class ="navbar-nav">
                    <a class="nav-item nav-link" id="home-menu" href="#home">Home</a>
                    <a class="nav-item nav-link" id="about-menu" href="#about">Sobre Nós</a>
                    <a class="nav-item nav-link" id="services-menu" href="#services">Serviços</a>
                    <a class="nav-item nav-link" id="contact-menu" href="#contact">Contato</a>
                    <a class="nav-item nav-link" id="login-menu" href="modal_login.php">Login</a>
                    <a class="nav-item nav-link" id="cadastro-menu" href="cadastro.php">Cadastro</a>
                </div>
            </div>
        </nav>
    </div>
</header>